export const EPORN_CATEGORIES = [
    "4K Ultra HD",
    "60 FPS",
    "Amateur",
    "Anal",
    "Asian",
    "ASMR",
    "BBW",
    "BDSM",
    "Big Ass",
    "Big Dick",
    "Big Tits",
    "Bisexual",
    "Blonde",
    "Blowjob",
    "Bondage",
    "Brunette",
    "Bukkake",
    "Creampie",
    "Cumshot",
    "Double Penetration",
    "Ebony",
    "Fat",
    "Fetish",
    "Fisting",
    "Footjob",
    "For Women",
    "Gay",
    "Group Sex",
    "Handjob",
    "Hardcore",
    "HD Porn 1080p",
    "HD Sex",
    "Hentai",
    "Homemade",
    "Hotel",
    "Housewives",
    "HQ Porn",
    "Indian",
    "Interracial",
    "Japanese",
    "Latina",
    "Lesbian",
    "Lingerie",
    "Massage",
    "Masturbation",
    "Mature",
    "MILF",
    "Nurses",
    "Office",
    "Older Men",
    "Orgy",
    "Outdoor",
    "Petite",
    "Pornstar",
    "POV",
    "Public",
    "Redhead",
    "Shemale",
    "Sleep",
    "Small Tits",
    "Squirt",
    "Striptease",
    "Students",
    "Swinger",
    "Teen",
    "Threesome",
    "Toys",
    "Uncategorized",
    "Uniform",
    "Vintage",
    "VR Porn",
    "Webcam"
];
